PastaLaVistaBaby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('WebsiteApp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebsiteApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('menu/', views.menu, name='menu'),
    path('ordering/', views.ordering, name='ordering'),
    path('order_management/', views.order_management, name='order_management'),
    path('order_place/', views.order_place, name='order_place'),
    path('order_remove/', views.order_remove, name='order_remove'),
    path('food_json/', views.food_json, name='food_json'),
    path('orders_json/', views.orders_json, name='orders_json'),
    path('reserve_table/', views.reserve_table, name='reserve_table'),
]

WebsiteApp/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.forms import ModelForm

upload_storage = FileSystemStorage(
    location=settings.STATIC_ROOT, base_url='/static/')


# Create your models here.


class FoodCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class FoodModel(models.Model):
    title = models.CharField(max_length=160)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/food/', storage=upload_storage)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    weight = models.CharField(max_length=8)  # in grams
    category = models.ForeignKey(FoodCategory, on_delete=models.CASCADE, null=True)
    in_stock = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class OrderModel(models.Model):
    completed = models.BooleanField(default=False)
    full_name = models.CharField(max_length=160)
    phone_number = models.CharField(max_length=20)
    delivery_type = models.CharField(
        max_length=1, choices=(('1', 'Delivery'), ('2', 'Pickup')))
    delivery_address = models.CharField(max_length=160, blank=True)
    payment_type = models.CharField(
        max_length=1, choices=(('1', 'Cash'), ('2', 'Card')))
    amount_of_tools = models.IntegerField(blank=True)
    comment = models.TextField(blank=True)
    order_time = models.TimeField(auto_now_add=True)
    food_id_list = models.JSONField(default=list)
    total_cost = models.DecimalField(max_digits=9, decimal_places=2)


class ReservationModel(models.Model):
    full_name = models.CharField(max_length=160)
    phone_number = models.CharField(max_length=20)
    reservation_time = models.DateTimeField(auto_now_add=True)
    reserved_for = models.DateTimeField()


class OrderForm(ModelForm):
    class Meta:
        model = OrderModel
        fields = ['full_name', 'phone_number', 'delivery_type',
                 'delivery_address', 'payment_type', 'amount_of_tools', 'comment']

class ReservationForm(ModelForm):
    class Meta:
        model = ReservationModel
        fields = ['full_name', 'phone_number', 'reserved_for']

WebsiteApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseBadRequest
from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import BadRequest

from datetime import datetime
import hashlib
import pytz
import json

from .models import FoodModel, OrderModel, OrderForm, FoodCategory, ReservationForm, ReservationModel

# Create your views here.


def index(request):
    # print(dir(request))
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def menu(request):
    ctx = {'menu': FoodModel.objects.filter(in_stock=True).order_by('category', 'title'), 'categories': FoodCategory.objects.all()}
    return render(request, 'menu.html', context=ctx)


def contact(request):
    return render(request, 'contact.html')


def ordering(request):
    return render(request, 'ordering.html')


def order_success(request):
    return render(request, 'order_success.html')


@staff_member_required
def order_management(request):
    ctx = {}
    ctx['orders'] = OrderModel.objects.filter(completed=False)
    ctx['food_lookup'] = {
        food.id: food.title for food in FoodModel.objects.all()}
    ctx['reservations'] = ReservationModel.objects.filter(reserved_for__gte=datetime.now())

    return render(request, 'order_management.html', context=ctx)


def respond(msg, error=False):
    return HttpResponse(
        json.dumps({'error': error, 'message': msg}),
        content_type='application/json')


def order_place(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            total_price = 0
            food_ids = []
            menuc = request.COOKIES.get('menu')
            if not menuc:
                return BadRequest()

            for foodentry in menuc.split(','):
                if not foodentry:
                    continue

                quantity, foodid = foodentry.split('x')
                food = FoodModel.objects.get(id=foodid)
                if not food or not food.in_stock:
                    return respond(f'Food {foodid} not found or out of stock', True)

                total_price += food.price * int(quantity)
                food_ids.append((int(quantity), int(foodid)))

            model = form.save(commit=False)

            model.food_id_list = food_ids
            model.total_cost = total_price

            model.save()
            form.save_m2m()
            return respond(form.cleaned_data['full_name'] + ', Ваше замовлення підтверджено! Очікуйте. Дякуємо, що обираєте Pasta la Vista!')
        else:
            print(form.errors)
            return HttpResponseBadRequest("Invalid form")
    return HttpResponseNotAllowed(['POST'])


@staff_member_required
def order_remove(request):
    if request.method == 'POST':
        id = request.POST.get('order_id', None)
        if id:
            obj = OrderModel.objects.get(id=id)
            obj.completed = True
            obj.save()
        return redirect('order_management')


def food_json(request):
    food_list = FoodModel.objects.all()
    food_dict = {
        food.id: {
            'title': food.title,
            'price': str(food.price),
            'weight': str(food.weight),
            'image': food.image.url,
        } for food in food_list
    }
    return HttpResponse(
        json.dumps(food_dict), content_type='application/json')

@staff_member_required
def orders_json(request):
    order_list = OrderModel.objects.filter(completed=False)
    reservation_list = ReservationModel.objects.filter(reserved_for__gte=datetime.now())
    # Make a unique hash
    uniq_str = ''
    for order in order_list:
        uniq_str += str(order.id) + str(order.total_cost) + str(order.food_id_list) + order.phone_number + order.full_name + ' '
    for reservation in reservation_list:
        uniq_str += str(reservation.id) + str(reservation.reserved_for) + reservation.phone_number + reservation.full_name + ' '

    algo = hashlib.sha512(uniq_str.encode('utf-8'), usedforsecurity=False).hexdigest()
    return HttpResponse(
        json.dumps({'hash': algo}), content_type='application/json')


def test(request):
    return render(request, 'test.html')

def reserve_table(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            print("Saving form")
            form.save()
            return respond("Бронювання підтверджено! Чекаємо на вас у зазначений нас в нашому ресторані! Дякуємо, що обираєте Pasta la Vista!")

        else:
            print(form.errors)
            return HttpResponseBadRequest("Invalid form")
    return HttpResponseNotAllowed(['POST'])

WebsiteApp/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}About us{% endblock %}
{% block static_files %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
<section class="about__us">
  <div class="about__us__container _container">
    <div class="about__us__header header-block">
      <div class="about__us__titile header-block__title header-block__title_mod"><h2>Про нас</h2></div>
    </div>
    <div class="about__us__body">
      <div class="about__us__image">
        <img src="{% static 'images/about__us/Img01.jpg' %}" alt="">
      </div>
      <div class="about__us__content">
        <div class="about__us__text">
          <p>Як ми можемо зробити людей трішечки щасливішими? </p>

          <p>Завдяки старанню наших поварів і пастамейкерів, що готують без перебільшення - найсмачнішу пасту. В Черкасах!</p>

          <p>Всю пасту та равіолі ми робимо вручну на відкритій кухні і завітавши до нас, ви можете спостерігати за цим магічним процесом. То є окремий вид медитації.</p>

          <p>Ми працюємо виключно на італійському борошні твердих сортів пшениці, саме тому наша паста ніколи не розварюється,
          пружна і має характерну «твердинку», як кажуть італійці «Аль денте». </p>
        </div>
      </div>
    </div>
    <div class="about__us__body about__us__body_second">
      <div class="about__us__image about__us__image_second">
        <img src="{% static 'images/about__us/Img02.jpg' %}" alt="">
      </div>
      <div class="about__us__content about__us__content_second">
        <div class="about__us__text about__us__text_second">
          <p>
            Наші повара, в свою чергу, створюють ідеальні соуса, тому кожна страва має незабутній післясмак.
            А ще, власноруч, кожного ранку ми робимо найсмачніші круасани в місті.
            Спробуй їх з кавою nocciola (потім скажете дякую за цю рекомендацію).
            Доповнюють наше меню салати, сніданки та десерти на будь-який смак.
            Тут точно є чим вас порадувати і здивувати.
          </p>

          <p>
            Наша ціль - це покорити ваші смакові рецептори і назавжди залишитися у вашому серденьку.
            Спробуй Pasta la vista, baby!
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="page__instagram instagram">
  <div class="instagram__container _container">
    <div class="instagram__header header-block">
      <div class="header-block__title"><h2>Ми в Instagram</h2></div>
      <div class="header-block__subtitle">Заходьте на нашу сторінку в Instagram. Там багато цікавого.</div>
      <div class="header-block__button block-button block-button_center">
        <a href="https://www.instagram.com/plv_baby/" target="_blank">Instagram</a>
      </div>
    </div>

    <div class="Instagram__body">
      <div class="Instagram__items">
        <div class="Instagram__item Instagram__item_01">
          <a href="https://www.instagram.com/p/CZWOf70AR3v/"  target="_blank" class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication1.png' %}" alt="Instagram Picture">
          </a>
          <a href="https://www.instagram.com/p/CZJzcgdI3qi/"  target="_blank"class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication2.png' %}" alt="Instagram Picture">
          </a>
        </div>

        <div class="Instagram__item Instagram__item_02">
          <a href="https://www.instagram.com/p/CZMQumTIuBl/"  target="_blank" class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication3.png' %}" alt="Instagram Picture">
          </a>
          <a href="https://www.instagram.com/p/CZokjSyAw01/" target="_blank" class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication4.png' %}" alt="Instagram Picture">
          </a>
        </div>

        <div class="Instagram__item Instagram__item_03">
          <a href="https://www.instagram.com/p/CZB1J1PI2Nn/" target="_blank" class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication5.png' %}" alt="Instagram Picture">
          </a>
          <a href="https://www.instagram.com/p/CaPGkCSAKZT/" target="_blank" class = Instagram__publication>
            <img src="{% static 'images/instagram/Publication6.png' %}" alt="Instagram Picture">
          </a>
        </div>

        <div class="Instagram__item Instagram__item_04">
          <a href="https://www.instagram.com/p/CenvuSEoTfm/" target="_blank"
          class = Instagram__publication Instagram__publication_last>
            <img src="{% static 'images/instagram/Publication7.png' %}" alt="Instagram Picture">
          </a>
          <a href="https://www.instagram.com/p/CXQYQg_Ivet/" target="_blank"
          class = Instagram__publication Instagram__publication_last>
            <img src="{% static 'images/instagram/Publication8.png' %}" alt="Instagram Picture">
          </a>
        </div>
    </div>
  </div>
</section>

{% endblock %}

WebsiteApp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;600;700&family=Nunito:wght@300;500;600;700&display=swap" rel="stylesheet">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16"  href="{% static 'images/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#ffffff">
  {% block static_files %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">

  <title>{% block title %}Base template{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
  <noscript>
    <div class="noscript">
      <p>You need to enable JavaScript to run this app.</p>
    </div>
  </noscript>

  <div class="wrapper">
    {% include "base/header.html" %}

    <main class="page">
      {% include "base/popups.html" %}

      {% block content %}{% endblock %}
    </main>

    {% include "base/footer.html" %}
  </div>

  <script src="{% static 'js/base.js' %}"></script>
  {% block scripts %}{% endblock %}

  <!-- Hidden urls to stuff inaccessible in JS -->

  <div class="hidden_button_links" style="display: none;">
    <p id="button_remove_svg">{% static 'images/cart/close.svg' %}</p>
    <p id="button_plus_svg">{% static 'images/cart/plus.svg' %}</p>
    <p id="button_minus_svg">{% static 'images/cart/minus.svg' %}</p>
  </div>

  <p id="hidden-reservation-url" style="display: none">{% url 'reserve_table' %}</p>

  <div id="hidden-csrf-box" style="display: none;">
    {% csrf_token %}
  </div>

  <div id="hidden-img-del1" style="display: none;">{% static 'images/format/Glovo_Logo.png' %}</div>
  <div id="hidden-img-del2" style="display: none;">{% static 'images/format/Mister.Am_Logo.png' %}</div>

</body>
</html>

WebsiteApp/templates/base/footer.html
{% load static %}
<footer class="footer">
  <div class="footer__container _container">
    <div class="footer__content">
      <div class="our-menu__text header-block__subtitle">Чекаємо на ваші відгуки та відмітки у соціальних мережах!</div>

      <div class="footer__items">
        <div class="our-menu__button block-button block-button_footer">
          <a href="https://www.instagram.com/plv_baby/" target="_blank">Instagram</a>
        </div>

        <div class="our-menu__button">
          <a href="javascript:void(0)" onclick="javascript:scrollToTop()">
            <img src="{% static 'images/footer/Arrow.svg' %}" alt="Arrow">
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

WebsiteApp/templates/base/header.html
{% load static %}
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<header class="header">
  <nav class="navbar">
    <div class="navbar__container _container">
      <div class="nav__wrap">
        <a href="{% url 'index' %}" class="Logo" id="Logo">
          <img src="{% static 'images/header/logo.svg' %}" alt="Logo">
        </a>

        <ul class="menu" id="menu">
          <li><a class = "menu__text" id="header_link_about" href="{% url 'about' %}">Про нас</a></li>
          <li><a class = "menu__text" id="header_link_menu" href="{% url 'menu' %}">Меню</a></li>
          <li><a class = "menu__text" id="header_link_contacts" href="{% url 'contact' %}">Контакти</a></li>
          <li><a class = "menu__text" id="header_link_reservation" href="javascript:void(0)" onclick="javascript:openReservation()">Резерв столу</a>
          </li>
        </ul>

        <ul class="menu__items">
          <a href="tel:+380631407000" class="menu__item">
            <img src="{% static 'images/header/Tel.svg' %}" alt="Tel">
          </a>

          <a href="#popup__cart" class="menu__item menu__item_cart" onclick="javascript:popupOpened()">
            <img src="{% static 'images/header/Cart.svg' %}" alt="Cart(3)">
            <div class="menu__item__cart__number">

            </div>
          </a>
        </ul>

        <div class="hamb">
          <a href="#popup__cart" class="menu__cart">
            <img class = "cart2" src="{% static 'images/header/Cart.svg' %}" alt="Cart">
            <div class="menu__item__cart__number2">
              1
            </div>
          </a>
          <div class="hamb__field" id="hamb">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="popup" id="popup"></div>
</header>

WebsiteApp/templates/base/popups.html
{% load static %}

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<div class="popup__cart" id="popup__cart">
  <a href="#" class="popup__cart__area" onclick="javascript:popupClosed()"></a>
  <div class="popup__cart__body">
    <div class="popup__cart__content">
      <div class="popup__cart__header">
        <div class="popup__cart__title">Корзина</div>
        <a href="#" class="popup__cart__close" onclick="javascript:popupClosed()">
          <img src="{% static 'images/header/Close2.svg' %}" alt="">
        </a>
      </div>

      <div class="cart__hr cart__hr_mod"></div>

      <div class="popup__cart__empty">
        <div class="popup__cart__empty__title">Ваша корзина зараз порожня!</div>
        <div class="popup__cart__empty__text">
          Перейдіть в розділ “меню” та додайте бажані страви.
        </div>
      </div>
      <ol class="popup__cart__list">
      </ol>



      <div class="popup__cart__price">
        <div class="popup__cart__price__text">Ціна:</div>
        <div class="popup__cart__price__price">
          <div class="popup__cart__price__price1"></div>
          <div class="popup__cart__price__price2">грн</div>
        </div>
      </div>

      <div class="popup__cart__button" id="cart-button-order">
        <a href="{% url 'ordering' %}">Оформити замовлення</a>
      </div>
      <div class="popup__cart__button" id="cart-button-menu">
        <a href="{% url 'menu' %}">Перейти в меню</a>
      </div>


    </div>
  </div>
</div>

<!-- <div id="popup__reservation" class="popup__reservation">
  <a href="#" class="popup__reservation__area" onclick="javascript:popupClosed()"></a>
  <div class="popup__reservation__body">
    <div class="popup__reservation__content">
      <a href="#" class="popup__reservation__close" onclick="javascript:popupClosed()">
        <img src="{% static 'images/header/Close.svg' %}" alt="">
      </a>
      <form action="{% url 'reserve_table' %}" id="reservation-form" method="POST">
        {% csrf_token %}
        <p class="form__reservation__text">Ваше ім’я*</p>
        <input class="form__reservation__input" type="text" id="full_name" name="full_name" placeholder="Введіть ваше ім’я">

        <p class="form__reservation__text">Телефон*</p>
        <input class="form__reservation__input" type="tel" name="phone_number"
        pattern="+380[0-9]{3}-[0-9]{3}" placeholder="Введіть ваш телефон">

        <p class="form__reservation__text">Дата/Час*</p>
        <input class="form__reservation__date" type="datetime-local" name="reserved_for">
        <div class="form__reservation__button">
          <a href="javascript:void(0)" onclick="submitReservation()">Зарезервувати</a>
        </div>
      </form>
    </div>
  </div>
</div> -->

WebsiteApp/templates/base/slider.html
<!-- {% load static %}

<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<div class="main-slider">
  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/slider.js' %}"></script>
 -->

WebsiteApp/templates/base/slider_menu.html
<!-- {% load static %}

<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
<link rel="stylesheet" href="{% static 'css/slider_menu.css' %}">
<div class="main-slider">
  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>

  <div class="slide">
    <div class="slide__image">
      <img src="{% static 'images/slider/bg.jpg' %}" alt="">
    </div>

    <div class="slider__content">
      <div class="slider__title">Відкрита вакансія - касир-бариста!
      </div>

      <div class="slider__suptitle">
        • бажано з досвідом роботи <br>
        • вік від 20 років
      </div>
      <div class="slider__button">
        <a href="tel:+380631407000">+380 63 140 7000</a>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/slider.js' %}"></script> -->

WebsiteApp/templates/menu.html
{% extends "base.html" %}
{% load static %}

{% block title %}Menu{% endblock %}

{% block static_files %}
  <link rel="stylesheet" href="{% static 'css/menu.css' %}">
  <script src="{% static 'js/menu.js' %}"></script>
{% endblock %}

{% block content %}
{% include "base/slider_menu.html" %}
<section class="menu__page menu1">
  <div class="menu1__container _container">
    <div class="menu1__classes">
      <a href="javascript:void(0)" onclick="selectCategory('all')">
        <div class="menu1__class menu1__class_selected menu1__class_all">
          Усі
        </div>
      </a>
      {% for cat in categories %}
      <a href="javascript:void(0)" onclick="selectCategory('{{ cat.id }}')">
        <div class="menu1__class" id="category-selector-{{ cat.id }}">
          {{ cat.name }}
        </div>
      </a>
      {% endfor %}
    </div>

    <div class="menu1__items">
      {% for cat in categories %}
        <div class="menu1__category_items" id="category-{{ cat.id }}">
          <div class="menu1__category_title"><h1>{{ cat.name }}</h1></div>
          <div class="menu1__item__column">
          {% for item in cat.foodmodel_set.all %}
            {% if item.in_stock %}

            <div class="menu1__item item-menu food-category-{{ item.category.id }}" id="menu-item-{{ item.id }}">
                <div class="item-menu__image">
                  <img src="{% get_static_prefix %}{{ item.image }}" alt="{{ item.title }}">
                  <div class="item-menu__image__weight">{{ item.weight }}</div>
                </div>
                <div class="item-menu__content">
                  <div class="item-menu__title">{{ item.title }}</div>
                  <div class="item-menu__text">{{ item.description }}</div>
                  <div class="item-menu__price">
                    <div class="item-menu__price__text">{{ item.price }} грн</div>
                    <div class="item-menu__price__cart">
                      <a href="javascript:menuItemClicked({{ item.id }})">
                        <img src="{% static 'images/menu/Cart_Icon.svg' %}" alt="">
                      </a>
                    </div> <!-- /.item-menu__price__cart -->
                  </div> <!-- item-menu__price -->
                </div> <!-- /.item-menu__content -->
            </div> <!-- .menu1__item -->
            {% endif %} <!-- if item.in_stock -->
          {% endfor %} <!-- end for item in cat.foodmodel_set.all -->
          </div> <!-- /.menu1__item__column -->
        </div> <!-- end of menu1__category_items -->
      {% endfor %} <!-- end for cat in categories -->
      <div class="menu1__item menu1__empty">
        <p>Поки що тут пустовато..</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}